name: freebsd

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  TRAVIS_OS_NAME: freebsd
  BUILD_TARGET: freebsd
  BUILD_TYPE: Release

jobs:
  build:
    if: "contains(github.event.commits[0].message, '[ci build]')"
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    uses: vmactions/freebsd-vm@v0.1.0
    with:
      envs: ""
      run: |
        travis/install.sh
        travis/build.sh
