name: linux

on:
  push:
    paths:
      - yasio/**/*
      - thirdparty/**/*
      - tests/**/*
      - examples/**/*
      - CMakeLists.txt
      - .github/workflows/linux-ci.yml
      - scripts/**/*
      - extensions/**/*

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  PING_HOST: github.com

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      shell: pwsh
      run: |
        ./scripts/build.ps1 -p linux -cm '-Bbuild','-DYASIO_ENABLE_HPERF_IO=1'
        ./scripts/test.ps1 -dir 'build' -target 'linux'
